### ISSUE TITLE
No SQL Template File

### ISSUE THREAD

**Issue by xiaoman1221** [MagmaBlock/LavaAnimeLibServerV2#4]
No SQL Template File
/opt/LavaAnimeLib/node_modules/mysql2/promise.js:356
    const localErr = new Error();
                     ^

Error: Table 'play_ce_studio.anime' doesn't exist
    at PromisePool.query (/opt/LavaAnimeLib/node_modules/mysql2/promise.js:356:22)
    at checkDB (file:///opt/LavaAnimeLib/common/sql.js:17:30)
    at file:///opt/LavaAnimeLib/common/sql.js:15:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sql: 'SELECT * FROM anime LIMIT 10',
  sqlState: '42S02',
  sqlMessage: "Table 'play_ce_studio.anime' doesn't exist"
}

Node.js v20.15.0

**Comment by MagmaBlock** [comment]
LavaAnimeLibV2 写的过于生猛，没有考虑自部署
自己部署基本是没法用的

---

你需要自己写数据库表结构，然后自己写个邀请码进数据库，注册，再把自己改成管理员。

添加动画也是很麻烦的，节点使用 Alist，目录结构参考：（这是 V3 的代码）
https://github.com/MagmaBlock/LavaAnimeLib/blob/4fdf16b0e82455a30410d25ddc24982c22c41a09/src/class/library/scraper/v2.ts#L8-L30

Alist 存放番剧文件夹完成后，执行 node ./task/main.js 刷新新番。目前应该就是这个流程，不过我不能确定还有什么地方写的有问题



SQL DDL 如下：

```sql
-- lavaanimelib.anime definition

CREATE TABLE `anime` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '文件夹ID',
  `year` text NOT NULL COMMENT '年',
  `type` text NOT NULL COMMENT '月',
  `name` text NOT NULL COMMENT '文件夹名称',
  `views` int NOT NULL DEFAULT '0' COMMENT '播放量',
  `bgmid` text COMMENT 'Bangumi ID',
  `nsfw` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'NSFW',
  `title` text COMMENT '番剧名',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `poster` text COMMENT '海报图片地址',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=886 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.bangumi_data definition

CREATE TABLE `bangumi_data` (
  `bgmid` int NOT NULL,
  `relations_anime` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `subjects` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `characters` longtext,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`bgmid`),
  UNIQUE KEY `bangumi_data_un` (`bgmid`),
  UNIQUE KEY `bgmid` (`bgmid`),
  UNIQUE KEY `bgmid_2` (`bgmid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.follow definition

CREATE TABLE `follow` (
  `user_id` int NOT NULL,
  `anime_id` int NOT NULL,
  `status` int NOT NULL,
  `edit_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.invite_code definition

CREATE TABLE `invite_code` (
  `code` varchar(100) NOT NULL,
  `code_user` int DEFAULT NULL,
  `code_creator` int DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `use_time` timestamp NULL DEFAULT NULL,
  `expiration_time` timestamp NULL DEFAULT NULL,
  UNIQUE KEY `invite_code_un` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.settings definition

CREATE TABLE `settings` (
  `key` varchar(100) NOT NULL,
  `value` text,
  UNIQUE KEY `settings_un` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.token definition

CREATE TABLE `token` (
  `token` varchar(256) NOT NULL,
  `user` int NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expiration_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  UNIQUE KEY `token` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.`user` definition

CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(100) NOT NULL,
  `name` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `data` varchar(2048) DEFAULT NULL,
  `settings` varchar(2048) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=198 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.view_history definition

CREATE TABLE `view_history` (
  `userID` int NOT NULL COMMENT '用户的 ID',
  `animeID` int NOT NULL COMMENT '动画的 ID',
  `fileName` varchar(255) DEFAULT NULL COMMENT '播放视频的名称（读操作时，可解析信息）',
  `episode` varchar(16) DEFAULT NULL COMMENT '播放视频的集数',
  `currentTime` int DEFAULT NULL COMMENT '播放视频的当前进度（如果有）',
  `totalTime` int DEFAULT NULL COMMENT '播放视频的总长度（如果有）',
  `userIP` varchar(64) DEFAULT NULL COMMENT '用户的播放 IP',
  `watchMethod` varchar(32) DEFAULT NULL COMMENT '用户播放方式',
  `lastReportTime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后一次上报观看的时间',
  `useDrive` varchar(64) DEFAULT NULL COMMENT '播放时的节点',
  UNIQUE KEY `view_history_un` (`userID`,`animeID`,`fileName`,`watchMethod`),
  KEY `view_history_userID_IDX` (`userID`,`animeID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.views definition

CREATE TABLE `views` (
  `id` int NOT NULL,
  `ep` text,
  `file` text,
  `ip` text,
  `user` int DEFAULT NULL,
  `time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `type` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- lavaanimelib.upload_message definition

CREATE TABLE `upload_message` (
  `id` int NOT NULL AUTO_INCREMENT,
  `index` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `animeID` int DEFAULT NULL,
  `bangumiID` int DEFAULT NULL,
  `fileName` text COLLATE utf8mb4_unicode_ci,
  `messageSentStatus` tinyint(1) NOT NULL DEFAULT '0',
  `uploadTime` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `upload_message_animeID_fkey` (`animeID`),
  KEY `upload_message_bangumiID_fkey` (`bangumiID`),
  CONSTRAINT `upload_message_animeID_fkey` FOREIGN KEY (`animeID`) REFERENCES `anime` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `upload_message_bangumiID_fkey` FOREIGN KEY (`bangumiID`) REFERENCES `bangumi_data` (`bgmid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1253 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by xiaoman1221** [comment]
问题不大，我玩会，可能还能给你v3贡献点东西啥的
